apiVersion: scan.reach/v1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-controller
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-sample
spec:
  # TODO(user): Add fields here
